### ISSUE TITLE
Screensaver turns on

### ISSUE THREAD

**Issue by ni1ight** [ni1ight/istrobot-stopwatch-ui#11]
We need to find a way how to disable screensaver during run of the application.

**Comment by alhafoudh** [comment]
Try this for Linux: http://stackoverflow.com/questions/14415742/prevent-monitor-from-entering-standby-on-linux 
Try this for MacOS: http://stackoverflow.com/questions/5596319/how-to-programmatically-prevent-a-mac-from-going-to-sleep/5596946#5596946

Try this for Windows:

```
#include <Windows.h>
void DisableScreenSaver()
{
  SetThreadExecutionState(EXECUTION_STATE.ES_DISPLAY_REQUIRED | 
  EXECUTION_STATE.ES_CONTINUOUS);
}
void EnableScreenSaver()
{
  SetThreadExecutionState(EXECUTION_STATE.ES_CONTINUOUS);
}
```

**Comment by ni1ight** [comment]
Thanks, I'll try it.

**Comment by ni1ight** [comment]
Done for Windows with the "SystemParametersInfo()" WINAPI function.

**Comment by ni1ight** [comment]
Closing, works on Windows and MAC, not necessary for Linux.
