### ISSUE TITLE
Start stopwatch without connecting serial port

### ISSUE THREAD

**Issue by alhafoudh** [ni1ight/istrobot-stopwatch-ui#7]
Right now app cannot be started without connecting to serial port

**Comment by ni1ight** [comment]
I did that on purpose. Do you have a proposal how to improve it?

**Comment by alhafoudh** [comment]
App should be able to be used without serial port if measurement hardware malfuctions

**Comment by ni1ight** [comment]
Ok, I'll take care of that.

**Comment by lijunwu001** [comment]
added offline mode!

**Comment by alhafoudh** [comment]
Great, but choosing "Offline mode" from combobox is little incovenient for me. What about adding button saying "Offline mode" next to "Connect" button?

**Comment by lijunwu001** [comment]
You are right, it's better with button. changed.

**Comment by alhafoudh** [comment]
Fantastic! :)
