### ISSUE TITLE
Crash when app is closed using ESC key on OSX

### ISSUE THREAD

**Issue by alhafoudh** [ni1ight/istrobot-stopwatch-ui#8]
When I close app by pressing ESC key, it crashed on OSX

make: Nothing to be done for `first'.

```
No serial selected.
Serial open confirmed.
casomiera(37720,0x7fffab5373c0) malloc: *** error for object 0x7fff595ea610: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Application Specific Information:
abort() called
*** error for object 0x7fff57ca6610: pointer being freed was not allocated
```

**Comment by ni1ight** [comment]
I probably know where the problem might be. Can you test it with older versions?

**Comment by alhafoudh** [comment]
I have just tested it, this commit introduced the bug: d1a90c93d4ae0d5d32a10f956157098ba654f27f

**Comment by ni1ight** [comment]
The problem is probably line 108, this->deletelater() should be replaced by this->close().

**Comment by ni1ight** [comment]
Changed, please try the latest version.

**Comment by alhafoudh** [comment]
Great, works!
