### ISSUE TITLE
App is missing fancy icon

### ISSUE THREAD

**Issue by alhafoudh** [ni1ight/istrobot-stopwatch-ui#9]
For example for Mac OS you need at least 1024x1024 icon resolution

**Comment by ni1ight** [comment]
Designed, just need to integrate.
![icon](https://cloud.githubusercontent.com/assets/17001931/25062700/50565884-21d1-11e7-852c-0325b3a46d6a.png)

**Comment by ni1ight** [comment]
Closing, solved for Windows and MAC, not necessary for Linux.
